// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yacitoahbedkouzsdjfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhY2l0b2FoYmVka291enNkamZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTIzNzYsImV4cCI6MjA3MTA4ODM3Nn0.SNGW7rbqEXG5M9wb1imRXwS3OnuWsqgapi_RLJNJxUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});